model dsmodelIterationSelect
  extends ProsNet.Fabian.Tests.Test_CoSES_5_Prosumers;
  annotation(__Dymola_SimulationIterationVariables={"PROSUMER2.cheVal_prim_prod.dp",
   "PROSUMER2.cheVal_prim_cons.dp", "PROSUMER2.pipe_prim_hot.orifice1.dp_fg", 
  "PROSUMER2.pipe_prim_hot.pipe.port_a.p", "PROSUMER2.pipe_prim_hot.pipe.statesFM[2].p",
   "PROSUMER2.pipe_prim_hot.pipe.statesFM[3].p", "PROSUMER2.pipe_prim_hot.pipe.statesFM[4].p",
   "PROSUMER2.pipe_prim_hot.pipe.statesFM[5].p", "PROSUMER2.pipe_prim_hot.pipe.statesFM[6].p",
   "PROSUMER2.pipe_prim_hot.pipe.statesFM[7].p", "PROSUMER2.pipe_prim_hot.pipe.statesFM[8].p",
   "PROSUMER2.pipe_prim_hot.pipe.statesFM[9].p", "PROSUMER2.pipe_prim_hot.pipe.port_b.p",
   "PROSUMER2.pipe_prim_hot.orifice2.dp_fg", "PROSUMER2.pump_prim_prod.port_a.p",
   "PROSUMER2.pipe_prim_cold.orifice1.dp_fg", "PROSUMER2.pipe_prim_cold.pipe.port_a.p",
   "PROSUMER2.pipe_prim_cold.pipe.statesFM[2].p", "PROSUMER2.pipe_prim_cold.pipe.statesFM[3].p",
   "PROSUMER2.pipe_prim_cold.pipe.statesFM[4].p", "PROSUMER2.pipe_prim_cold.pipe.statesFM[5].p",
   "PROSUMER2.pipe_prim_cold.pipe.statesFM[6].p", "PROSUMER2.pipe_prim_cold.pipe.statesFM[7].p",
   "PROSUMER2.pipe_prim_cold.pipe.statesFM[8].p", "PROSUMER2.pipe_prim_cold.pipe.statesFM[9].p",
   "PROSUMER2.pipe_prim_cold.pipe.port_b.p", "PROSUMER3.cheVal_prim_prod.dp", 
  "PROSUMER3.cheVal_prim_cons.dp", "PROSUMER3.pipe_prim_hot.orifice1.dp_fg", 
  "PROSUMER3.pipe_prim_hot.pipe.port_a.p", "PROSUMER3.pipe_prim_hot.pipe.statesFM[2].p",
   "PROSUMER3.pipe_prim_hot.pipe.statesFM[3].p", "PROSUMER3.pipe_prim_hot.pipe.statesFM[4].p",
   "PROSUMER3.pipe_prim_hot.pipe.statesFM[5].p", "PROSUMER3.pipe_prim_hot.pipe.statesFM[6].p",
   "PROSUMER3.pipe_prim_hot.pipe.statesFM[7].p", "PROSUMER3.pipe_prim_hot.pipe.statesFM[8].p",
   "PROSUMER3.pipe_prim_hot.pipe.statesFM[9].p", "PROSUMER3.pipe_prim_hot.pipe.port_b.p",
   "PROSUMER3.pipe_prim_hot.orifice2.dp_fg", "PROSUMER3.pump_prim_prod.port_a.p",
   "PROSUMER3.pipe_prim_cold.orifice1.dp_fg", "PROSUMER3.pipe_prim_cold.pipe.port_a.p",
   "PROSUMER3.pipe_prim_cold.pipe.statesFM[2].p", "PROSUMER3.pipe_prim_cold.pipe.statesFM[3].p",
   "PROSUMER3.pipe_prim_cold.pipe.statesFM[4].p", "PROSUMER3.pipe_prim_cold.pipe.statesFM[5].p",
   "PROSUMER3.pipe_prim_cold.pipe.statesFM[6].p", "PROSUMER3.pipe_prim_cold.pipe.statesFM[7].p",
   "PROSUMER3.pipe_prim_cold.pipe.statesFM[8].p", "PROSUMER3.pipe_prim_cold.pipe.statesFM[9].p",
   "PROSUMER3.pipe_prim_cold.pipe.port_b.p", "PROSUMER4.cheVal_prim_prod.dp", 
  "PROSUMER4.cheVal_prim_cons.dp", "PROSUMER4.pipe_prim_hot.orifice1.dp_fg", 
  "PROSUMER4.pipe_prim_hot.pipe.port_a.p", "PROSUMER4.pipe_prim_hot.pipe.statesFM[2].p",
   "PROSUMER4.pipe_prim_hot.pipe.statesFM[3].p", "PROSUMER4.pipe_prim_hot.pipe.statesFM[4].p",
   "PROSUMER4.pipe_prim_hot.pipe.statesFM[5].p", "PROSUMER4.pipe_prim_hot.pipe.statesFM[6].p",
   "PROSUMER4.pipe_prim_hot.pipe.statesFM[7].p", "PROSUMER4.pipe_prim_hot.pipe.statesFM[8].p",
   "PROSUMER4.pipe_prim_hot.pipe.statesFM[9].p", "PROSUMER4.pipe_prim_hot.pipe.port_b.p",
   "PROSUMER4.pipe_prim_hot.orifice2.dp_fg", "PROSUMER4.pump_prim_prod.port_a.p",
   "PROSUMER4.pipe_prim_cold.orifice1.dp_fg", "PROSUMER4.pipe_prim_cold.pipe.port_a.p",
   "PROSUMER4.pipe_prim_cold.pipe.statesFM[2].p", "PROSUMER4.pipe_prim_cold.pipe.statesFM[3].p",
   "PROSUMER4.pipe_prim_cold.pipe.statesFM[4].p", "PROSUMER4.pipe_prim_cold.pipe.statesFM[5].p",
   "PROSUMER4.pipe_prim_cold.pipe.statesFM[6].p", "PROSUMER4.pipe_prim_cold.pipe.statesFM[7].p",
   "PROSUMER4.pipe_prim_cold.pipe.statesFM[8].p", "PROSUMER4.pipe_prim_cold.pipe.statesFM[9].p",
   "PROSUMER4.pipe_prim_cold.pipe.port_b.p", "PROSUMER5.cheVal_prim_prod.dp", 
  "PROSUMER5.cheVal_prim_cons.dp", "Pipe_ID_4_pipe_hot_23.orifice1.dp_fg", 
  "Pipe_ID_4_pipe_hot_23.pipe.port_a.p", "Pipe_ID_4_pipe_hot_23.pipe.statesFM[2].p",
   "Pipe_ID_4_pipe_hot_23.pipe.statesFM[3].p", "Pipe_ID_4_pipe_hot_23.pipe.statesFM[4].p",
   "Pipe_ID_4_pipe_hot_23.pipe.statesFM[5].p", "Pipe_ID_4_pipe_hot_23.pipe.statesFM[6].p",
   "Pipe_ID_4_pipe_hot_23.pipe.statesFM[7].p", "Pipe_ID_4_pipe_hot_23.pipe.statesFM[8].p",
   "Pipe_ID_4_pipe_hot_23.pipe.statesFM[9].p", "Pipe_ID_4_pipe_hot_23.pipe.port_b.p",
   "Pipe_ID_4_pipe_hot_23.orifice2.dp_fg", "PROSUMER3.hot_prim.p", 
  "Pipe_ID_6_pipe_hot_34.orifice1.dp_fg", "Pipe_ID_6_pipe_hot_34.pipe.port_a.p",
   "Pipe_ID_6_pipe_hot_34.pipe.statesFM[2].p", "Pipe_ID_6_pipe_hot_34.pipe.statesFM[3].p",
   "Pipe_ID_6_pipe_hot_34.pipe.statesFM[4].p", "Pipe_ID_6_pipe_hot_34.pipe.statesFM[5].p",
   "Pipe_ID_6_pipe_hot_34.pipe.statesFM[6].p", "Pipe_ID_6_pipe_hot_34.pipe.statesFM[7].p",
   "Pipe_ID_6_pipe_hot_34.pipe.statesFM[8].p", "Pipe_ID_6_pipe_hot_34.pipe.statesFM[9].p",
   "Pipe_ID_6_pipe_hot_34.pipe.port_b.p", "Pipe_ID_6_pipe_hot_34.orifice2.dp_fg",
   "PROSUMER4.hot_prim.p", "Pipe_ID_8_pipe_hot_45.orifice1.dp_fg", 
  "Pipe_ID_8_pipe_hot_45.pipe.port_a.p", "Pipe_ID_8_pipe_hot_45.pipe.statesFM[2].p",
   "Pipe_ID_8_pipe_hot_45.pipe.statesFM[3].p", "Pipe_ID_8_pipe_hot_45.pipe.statesFM[4].p",
   "Pipe_ID_8_pipe_hot_45.pipe.statesFM[5].p", "Pipe_ID_8_pipe_hot_45.pipe.statesFM[6].p",
   "Pipe_ID_8_pipe_hot_45.pipe.statesFM[7].p", "Pipe_ID_8_pipe_hot_45.pipe.statesFM[8].p",
   "Pipe_ID_8_pipe_hot_45.pipe.statesFM[9].p", "Pipe_ID_8_pipe_hot_45.pipe.port_b.p",
   "Pipe_ID_8_pipe_hot_45.orifice2.dp_fg", "PROSUMER5.hot_prim.p", 
  "PROSUMER5.pipe_prim_hot.orifice1.dp_fg", "PROSUMER5.pipe_prim_hot.pipe.port_a.p",
   "PROSUMER5.pipe_prim_hot.pipe.statesFM[2].p", "PROSUMER5.pipe_prim_hot.pipe.statesFM[3].p",
   "PROSUMER5.pipe_prim_hot.pipe.statesFM[4].p", "PROSUMER5.pipe_prim_hot.pipe.statesFM[5].p",
   "PROSUMER5.pipe_prim_hot.pipe.statesFM[6].p", "PROSUMER5.pipe_prim_hot.pipe.statesFM[7].p",
   "PROSUMER5.pipe_prim_hot.pipe.statesFM[8].p", "PROSUMER5.pipe_prim_hot.pipe.statesFM[9].p",
   "PROSUMER5.pipe_prim_hot.pipe.port_b.p", "PROSUMER5.pipe_prim_hot.orifice2.dp_fg",
   "PROSUMER5.pump_prim_prod.port_a.p", "PROSUMER5.pipe_prim_cold.orifice1.dp_fg",
   "PROSUMER5.pipe_prim_cold.pipe.port_a.p", "PROSUMER5.pipe_prim_cold.pipe.statesFM[2].p",
   "PROSUMER5.pipe_prim_cold.pipe.statesFM[3].p", "PROSUMER5.pipe_prim_cold.pipe.statesFM[4].p",
   "PROSUMER5.pipe_prim_cold.pipe.statesFM[5].p", "PROSUMER5.pipe_prim_cold.pipe.statesFM[6].p",
   "PROSUMER5.pipe_prim_cold.pipe.statesFM[7].p", "PROSUMER5.pipe_prim_cold.pipe.statesFM[8].p",
   "PROSUMER5.pipe_prim_cold.pipe.statesFM[9].p", "PROSUMER5.pipe_prim_cold.pipe.port_b.p",
   "PROSUMER5.pipe_prim_cold.orifice2.dp_fg", "PROSUMER5.cold_prim.p", 
  "Pipe_ID_8_pipe_cold_45.orifice1.dp_fg", "Pipe_ID_8_pipe_cold_45.pipe.port_a.p",
   "Pipe_ID_8_pipe_cold_45.pipe.statesFM[2].p", "Pipe_ID_8_pipe_cold_45.pipe.statesFM[3].p",
   "Pipe_ID_8_pipe_cold_45.pipe.statesFM[4].p", "Pipe_ID_8_pipe_cold_45.pipe.statesFM[5].p",
   "Pipe_ID_8_pipe_cold_45.pipe.statesFM[6].p", "Pipe_ID_8_pipe_cold_45.pipe.statesFM[7].p",
   "Pipe_ID_8_pipe_cold_45.pipe.statesFM[8].p", "Pipe_ID_8_pipe_cold_45.pipe.statesFM[9].p",
   "Pipe_ID_8_pipe_cold_45.pipe.port_b.p", "Pipe_ID_8_pipe_cold_45.orifice2.dp_fg",
   "PROSUMER4.pipe_prim_cold.orifice2.dp_fg", "PROSUMER4.cold_prim.p", 
  "Pipe_ID_6_pipe_cold_34.orifice1.dp_fg", "Pipe_ID_6_pipe_cold_34.pipe.port_a.p",
   "Pipe_ID_6_pipe_cold_34.pipe.statesFM[2].p", "Pipe_ID_6_pipe_cold_34.pipe.statesFM[3].p",
   "Pipe_ID_6_pipe_cold_34.pipe.statesFM[4].p", "Pipe_ID_6_pipe_cold_34.pipe.statesFM[5].p",
   "Pipe_ID_6_pipe_cold_34.pipe.statesFM[6].p", "Pipe_ID_6_pipe_cold_34.pipe.statesFM[7].p",
   "Pipe_ID_6_pipe_cold_34.pipe.statesFM[8].p", "Pipe_ID_6_pipe_cold_34.pipe.statesFM[9].p",
   "Pipe_ID_6_pipe_cold_34.pipe.port_b.p", "Pipe_ID_6_pipe_cold_34.orifice2.dp_fg",
   "PROSUMER3.pipe_prim_cold.orifice2.dp_fg", "PROSUMER3.cold_prim.p", 
  "Pipe_ID_4_pipe_cold_23.orifice1.dp_fg", "Pipe_ID_4_pipe_cold_23.pipe.port_a.p",
   "Pipe_ID_4_pipe_cold_23.pipe.statesFM[2].p", "Pipe_ID_4_pipe_cold_23.pipe.statesFM[3].p",
   "Pipe_ID_4_pipe_cold_23.pipe.statesFM[4].p", "Pipe_ID_4_pipe_cold_23.pipe.statesFM[5].p",
   "Pipe_ID_4_pipe_cold_23.pipe.statesFM[6].p", "Pipe_ID_4_pipe_cold_23.pipe.statesFM[7].p",
   "Pipe_ID_4_pipe_cold_23.pipe.statesFM[8].p", "Pipe_ID_4_pipe_cold_23.pipe.statesFM[9].p",
   "Pipe_ID_4_pipe_cold_23.pipe.port_b.p", "Pipe_ID_4_pipe_cold_23.orifice2.dp_fg",
   "PROSUMER2.pipe_prim_cold.orifice2.dp_fg", "PROSUMER2.cold_prim.p", 
  "Pipe_ID_2_pipe_cold_12.orifice1.dp_fg", "Pipe_ID_2_pipe_cold_12.pipe.port_a.p",
   "Pipe_ID_2_pipe_cold_12.pipe.statesFM[2].p", "Pipe_ID_2_pipe_cold_12.pipe.statesFM[3].p",
   "Pipe_ID_2_pipe_cold_12.pipe.statesFM[4].p", "Pipe_ID_2_pipe_cold_12.pipe.statesFM[5].p",
   "Pipe_ID_2_pipe_cold_12.pipe.statesFM[6].p", "Pipe_ID_2_pipe_cold_12.pipe.statesFM[7].p",
   "Pipe_ID_2_pipe_cold_12.pipe.statesFM[8].p", "Pipe_ID_2_pipe_cold_12.pipe.statesFM[9].p",
   "Pipe_ID_2_pipe_cold_12.pipe.port_b.p", "Pipe_ID_2_pipe_cold_12.orifice2.dp_fg",
   "PROSUMER1.cold_prim.p", "PROSUMER1.pipe_prim_cold.orifice2.dp_fg", 
  "PROSUMER1.pipe_prim_cold.pipe.port_b.p", "PROSUMER1.pipe_prim_cold.pipe.statesFM[9].p",
   "PROSUMER1.pipe_prim_cold.pipe.statesFM[8].p", "PROSUMER1.pipe_prim_cold.pipe.statesFM[7].p",
   "PROSUMER1.pipe_prim_cold.pipe.statesFM[6].p", "PROSUMER1.pipe_prim_cold.pipe.statesFM[5].p",
   "PROSUMER1.pipe_prim_cold.pipe.statesFM[4].p", "PROSUMER1.pipe_prim_cold.pipe.statesFM[3].p",
   "PROSUMER1.pipe_prim_cold.pipe.statesFM[2].p", "PROSUMER1.pipe_prim_cold.pipe.port_a.p",
   "PROSUMER1.pipe_prim_cold.orifice1.dp_fg", "PROSUMER1.pump_prim_prod.port_a.p",
   "Pipe_ID_2_pipe_hot_12.pipe.port_b.p", "Pipe_ID_2_pipe_hot_12.pipe.statesFM[9].p",
   "Pipe_ID_2_pipe_hot_12.pipe.statesFM[8].p", "Pipe_ID_2_pipe_hot_12.pipe.statesFM[7].p",
   "Pipe_ID_2_pipe_hot_12.pipe.statesFM[6].p", "Pipe_ID_2_pipe_hot_12.pipe.statesFM[5].p",
   "Pipe_ID_2_pipe_hot_12.pipe.statesFM[4].p", "Pipe_ID_2_pipe_hot_12.pipe.statesFM[3].p",
   "Pipe_ID_2_pipe_hot_12.pipe.statesFM[2].p", "Pipe_ID_2_pipe_hot_12.pipe.port_a.p",
   "Pipe_ID_2_pipe_hot_12.orifice1.dp_fg", "PROSUMER1.hot_prim.p", 
  "PROSUMER1.pipe_prim_hot.orifice1.dp_fg", "PROSUMER1.pipe_prim_hot.pipe.port_a.p",
   "PROSUMER1.pipe_prim_hot.pipe.statesFM[2].p", "PROSUMER1.pipe_prim_hot.pipe.statesFM[3].p",
   "PROSUMER1.pipe_prim_hot.pipe.statesFM[4].p", "PROSUMER1.pipe_prim_hot.pipe.statesFM[5].p",
   "PROSUMER1.pipe_prim_hot.pipe.statesFM[6].p", "PROSUMER1.pipe_prim_hot.pipe.statesFM[7].p",
   "PROSUMER1.pipe_prim_hot.pipe.statesFM[8].p", "PROSUMER1.pipe_prim_hot.pipe.statesFM[9].p",
   "PROSUMER1.pipe_prim_hot.pipe.port_b.p", "PROSUMER1.pipe_prim_hot.orifice2.dp_fg",
   "PROSUMER1.cheVal_prim_cons.dp", "PROSUMER1.cheVal_prim_prod.dp", 
  "Pipe_ID_2_pipe_hot_12.orifice2.dp_fg", "PROSUMER1.cheVa_sec_cons.dp", 
  "PROSUMER1.cheVal_sec_prod.dp", "PROSUMER2.cheVa_sec_cons.dp", 
  "PROSUMER2.cheVal_sec_prod.dp", "PROSUMER3.cheVa_sec_cons.dp", 
  "PROSUMER3.cheVal_sec_prod.dp", "PROSUMER4.cheVa_sec_cons.dp", 
  "PROSUMER4.cheVal_sec_prod.dp", "PROSUMER5.cheVa_sec_cons.dp", 
  "PROSUMER5.cheVal_sec_prod.dp"});
end dsmodelIterationSelect;
